apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-pv-claim
  labels:
    app: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
