apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-conf
  labels:
    app: grafana-datasource-conf
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus.monitoring.svc:8080",
                "version": 1,
                "user": "admin",
                "secureJsonData": {
                  "password": "QDPf-gjJLBAv4fRXCqxAr@Vg"
                }
            }
        ]
    }