apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: personal-website-pv-claim
  labels:
    app: personal-website
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
